server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        name: spring-security-manager
      # 8小时   8*60*60 =28800(s)
      # session 有效时间配置在 HttpSessionConfig 文件中
      # 这里没有生效,暂未找到原因
      timeout: 28800

spring:
       # jdbc
       datasource:
          driverClassName: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/authority?useUnicode=true&characterEncoding=utf-8
          username: root
          password: root
       # redis
       redis:
         database: 0
         host: localhost
         port: 6379
         password:

# mybatis plus
mybatis-plus:
         config-location: classpath:mybatis/mybatis-config.xml
         mapper-locations: classpath:com/springboot/security/mapper/xml/*.xml
#logging:
#  level:
#    root: debug
#    com.springboot.security: debug
